name: Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.headless -t ${{ secrets.DOCKER_USERNAME }}/pob-http-server:1.0.0 .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pob-http-server:1.0.0
